// GENERATED by `npm run matcher:train` — do not edit by hand.
// Deterministic logistic fit (seeded GD) over the OBF catalog; regenerate after
// the catalog changes. This is the live matcher scorer (see score.ts).
// Feature order: gtinExact, nameJaroWinkler, nameTokenSet, brandMatch, ingredientsOverlap, sizeMatch, variantConflict — each feature is two columns, [value, present].
// Held-out synthetic test: acc 100% F1 100%. Hand-labeled eval: acc 100% F1 100%.
import type { LogisticModel } from './logistic';

export const MATCHER_MODEL: LogisticModel = {
  weights: [1.151206, 1.151206, 0.473485, -1.427488, 6.03039, -1.427488, 2.48339, -1.430472, 1.343865, -0.902207, 2.191858, -1.377667, -1.088814, -1.088814],
  bias: -2.170088,
  threshold: 0.886778,
};
