// GENERATED by `npm run matcher:train` — do not edit by hand.
// Deterministic logistic fit (seeded GD) over the OBF catalog; regenerate after
// the catalog changes. This is the live matcher scorer (see score.ts).
// Feature order: gtinExact, nameJaroWinkler, nameTokenSet, brandMatch, ingredientsOverlap, sizeMatch, variantConflict — each feature is two columns, [value, present].
// Held-out synthetic test: acc 100% F1 100%. Hand-labeled eval: acc 100% F1 100%.
import type { LogisticModel } from './logistic';

export const MATCHER_MODEL: LogisticModel = {
  weights: [1.167477, 1.167477, 0.508857, -1.389958, 6.049761, -1.389958, 2.27576, -1.390085, 1.24697, -0.88924, 2.128385, -1.396999, -1.615572, -1.615572],
  bias: -2.11573,
  threshold: 0.884912,
};
