// GENERATED by `npm run matcher:train` — do not edit by hand.
// Deterministic logistic fit (seeded GD) over the OBF catalog; regenerate after
// the catalog changes. This is the live matcher scorer (see score.ts).
// Feature order: gtinExact, nameJaroWinkler, nameTokenSet, brandMatch, ingredientsOverlap, sizeMatch, variantConflict — each feature is two columns, [value, present].
// Held-out synthetic test: acc 100% F1 100%. Hand-labeled eval: acc 100% F1 100%.
import type { LogisticModel } from './logistic';

export const MATCHER_MODEL: LogisticModel = {
  weights: [1.120789, 1.120789, 0.83305, -1.118733, 6.00276, -1.118733, 2.09109, -2.268213, 1.389039, -0.661468, 1.861667, -1.405016, -1.58655, -1.58655],
  bias: -1.719905,
  threshold: 0.866257,
};
