// Train the logistic matcher on labeled pairs bootstrapped from the real catalog.
//
// Pipeline (all pure pieces from /lib/matcher):
//   1. loadMatchContext()        → the canonical catalog + brands
//   2. generateLabeledPairs()    → self-positives + same-block hard negatives
//   3. split train / test        → deterministic, by seeded shuffle
//   4. trainLogistic()           → fit weights by gradient descent
//   5. bestThreshold() on train  → set the decision threshold
//   6. evaluate() on the held-out synthetic split AND on the hand-labeled
//      EVAL_PAIRS (eval-pairs.ts) — the honest generalization check
//   7. write lib/matcher/model.json (the artifact a future score.ts can load)
//
// The default score.ts hand scorer is left in place; swapping this model in also
// means adopting model.threshold on the probability scale (see logistic.ts).
//
// Run (needs DATABASE_URL + the .ts hook):
//   npm run matcher:train
//   npm run matcher:train -- --pos 4 --neg 4 --epochs 1500 --lr 0.5 --seed 7

import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { prismaRepository } from '../lib/data/prisma-repository';
import { computeFeatures } from '../lib/matcher/features';
import { FEATURE_WEIGHTS } from '../lib/matcher/score';
import {
  bestThreshold,
  evaluate,
  featuresToVector,
  FEATURE_ORDER,
  predictProbaVector,
  trainLogistic,
  type Metrics,
} from '../lib/matcher/logistic';
import { generateLabeledPairs, mulberry32, toDataset } from '../lib/matcher/labeling';
import { EVAL_BRANDS, EVAL_PAIRS } from '../lib/matcher/eval-pairs';

interface Args {
  pos: number;
  neg: number;
  epochs: number;
  lr: number;
  l2: number;
  seed: number;
  testFrac: number;
}

function parseArgs(argv: string[]): Args {
  const a: Args = { pos: 3, neg: 3, epochs: 1200, lr: 0.5, l2: 1e-3, seed: 1234, testFrac: 0.2 };
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i];
    const next = () => Number(argv[++i]);
    if (k === '--pos') a.pos = next();
    else if (k === '--neg') a.neg = next();
    else if (k === '--epochs') a.epochs = next();
    else if (k === '--lr') a.lr = next();
    else if (k === '--l2') a.l2 = next();
    else if (k === '--seed') a.seed = next();
    else if (k === '--test-frac') a.testFrac = next();
  }
  return a;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const { catalog, brands } = await prismaRepository.loadMatchContext();

  const pairs = generateLabeledPairs(catalog, brands, {
    positivesPerProduct: args.pos,
    negativesPerProduct: args.neg,
    keepGtinFraction: 0.4,
    rng: mulberry32(args.seed),
  });

  // Deterministic shuffle + split.
  const shuffleRng = mulberry32(args.seed ^ 0x9e3779b9);
  const shuffled = [...pairs].sort(() => shuffleRng() - 0.5);
  const cut = Math.floor(shuffled.length * (1 - args.testFrac));
  const trainPairs = shuffled.slice(0, cut);
  const testPairs = shuffled.slice(cut);

  const train = toDataset(trainPairs);
  const test = toDataset(testPairs);
  const posCount = train.y.filter((v) => v === 1).length;

  const model = trainLogistic(train.X, train.y, {
    epochs: args.epochs,
    learningRate: args.lr,
    l2: args.l2,
  });

  // Threshold from the training split, then freeze it on the model.
  const trainProbs = train.X.map((x) => predictProbaVector(model, x));
  const tuned = bestThreshold(trainProbs, train.y);
  model.threshold = tuned.threshold;

  const testProbs = test.X.map((x) => predictProbaVector(model, x));
  const testMetrics = evaluate(testProbs, test.y, model.threshold);

  const evalProbs = EVAL_PAIRS.map((p) =>
    predictProbaVector(model, featuresToVector(computeFeatures(p.a, p.b, EVAL_BRANDS))),
  );
  const evalY = EVAL_PAIRS.map((p) => (p.isMatch ? 1 : 0));
  const evalMetrics = evaluate(evalProbs, evalY, model.threshold);

  report(args, catalog.length, trainPairs.length, testPairs.length, posCount, model, testMetrics, evalMetrics);
  printEvalErrors(evalProbs, model.threshold);
  printWeights(model);

  const artifactPath = path.join('lib', 'matcher', 'model.ts');
  await writeFile(artifactPath, renderModelModule(model, testMetrics, evalMetrics));
  console.log(`\nwrote ${artifactPath}`);

  await disconnect();
}

/**
 * Render the fitted model as a committed TS constant `score.ts` imports. Values
 * are rounded so re-runs on an unchanged catalog produce a byte-identical file
 * (no diff churn); no timestamp for the same reason.
 */
function renderModelModule(
  model: { weights: number[]; bias: number; threshold: number },
  test: Metrics,
  evalM: Metrics,
): string {
  const r6 = (x: number) => Number(x.toFixed(6));
  const weights = model.weights.map(r6).join(', ');
  return [
    '// GENERATED by `npm run matcher:train` — do not edit by hand.',
    '// Deterministic logistic fit (seeded GD) over the OBF catalog; regenerate after',
    '// the catalog changes. This is the live matcher scorer (see score.ts).',
    `// Feature order: ${FEATURE_ORDER.join(', ')} — each feature is two columns, [value, present].`,
    `// Held-out synthetic test: acc ${pct(test.accuracy)} F1 ${pct(test.f1)}. ` +
      `Hand-labeled eval: acc ${pct(evalM.accuracy)} F1 ${pct(evalM.f1)}.`,
    "import type { LogisticModel } from './logistic';",
    '',
    'export const MATCHER_MODEL: LogisticModel = {',
    `  weights: [${weights}],`,
    `  bias: ${r6(model.bias)},`,
    `  threshold: ${r6(model.threshold)},`,
    '};',
    '',
  ].join('\n');
}

function report(
  args: Args,
  catalogSize: number,
  nTrain: number,
  nTest: number,
  nPos: number,
  model: { bias: number; threshold: number },
  test: Metrics,
  evalM: Metrics,
) {
  console.log(
    `\nTRAIN-MATCHER  |  catalog ${catalogSize} products  |  pairs ${nTrain}+${nTest} ` +
      `(${nPos} train positives)  |  pos/neg per product ${args.pos}/${args.neg}\n`,
  );
  console.log(`threshold ${model.threshold.toFixed(3)}   bias ${model.bias.toFixed(3)}\n`);
  console.log(metricLine('held-out synthetic test', test));
  console.log(metricLine('hand-labeled eval       ', evalM));
}

function metricLine(label: string, m: Metrics): string {
  return (
    `${label}: acc ${pct(m.accuracy)}  P ${pct(m.precision)}  R ${pct(m.recall)}  F1 ${pct(m.f1)}  ` +
    `(tp ${m.tp} fp ${m.fp} tn ${m.tn} fn ${m.fn})`
  );
}

function printEvalErrors(evalProbs: number[], threshold: number) {
  const errs = EVAL_PAIRS.map((p, i) => ({ p, prob: evalProbs[i]! }))
    .filter(({ p, prob }) => (prob >= threshold ? 1 : 0) !== (p.isMatch ? 1 : 0));
  if (errs.length === 0) {
    console.log('\nno errors on the hand-labeled eval set.');
    return;
  }
  console.log(`\neval misses (${errs.length}):`);
  for (const { p, prob } of errs) {
    console.log(`  ${p.isMatch ? 'MATCH ' : 'NO    '} p=${prob.toFixed(2)}  ${p.note}`);
  }
}

function printWeights(model: { weights: number[] }) {
  console.log('\nlearned weights (value | present)   vs   hand weight:');
  FEATURE_ORDER.forEach((key, i) => {
    const valW = model.weights[i * 2]!;
    const presW = model.weights[i * 2 + 1]!;
    console.log(
      `  ${key.padEnd(18)} ${fmt(valW)} | ${fmt(presW)}    hand ${FEATURE_WEIGHTS[key].toFixed(1)}`,
    );
  });
}

function fmt(x: number): string {
  return (x >= 0 ? ' ' : '') + x.toFixed(2);
}

function pct(x: number): string {
  return `${(x * 100).toFixed(0)}%`;
}

async function disconnect() {
  const { prisma } = await import('../lib/data/prisma');
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
